### PR TITLE
Added Calmar and Sortino ratios

### PR DESCRIPTION
**Pull request by Anjum48**
As per issue https://github.com/pmorissette/ffn/issues/10. 

For the Calmar Ratio I used the method discussed here: http://investexcel.net/calmar-ratio/
For the Sortino Ratio I used this method: http://investexcel.net/calculate-the-sortino-ratio-with-excel/

I think I've implemented them correctly, but it might need a skilled eye to sense check it :)

### CODE REVIEW

**Comment by pmorissette** [comment]
Hey @Anjum48,

Sorry I didn't get back to you - totally lost track. Let me take a look and I will merge your commits in if all is well.

Thanks for your contribution!

Cheers,
Phil

**Comment by BlinkyBillToo** [comment]
I just updated to the latest FFN release (0.1.12), but I did not see these ratios included.

Any change they can be merged in anytime soon?

**Comment by sven337** [comment]
I'm interested in the Sortino ratio too. Phil, is this going to be merged?
Thanks!

**Comment by Anjum48** [comment]
Sorry guys - totally forgot about this. I'll submit the PR again and see if it'll merge

**Comment by pmorissette** [comment]
Sorry all - let me get on this asap!

**Comment by pmorissette** [comment]
Ok I merged it in and just refactored your code a bit afterwards. Now we have `calc_calmar_ratio` and `calc_sortino_ratio` as well in core.py.

Thanks again for your contribution and sorry for taking so long to reply.

**Comment by satoshi** [comment]
Hi,

Calmar ratio actually isn't CAGR / MaxDD.  What we have in ffn is called MAR:
https://www.rcmalternatives.com/2013/08/mar-and-calmar-ratios-identical-twins-with-opposite-personalities

Unlike MAR, Calmar uses (typically) 36 months to evaluate performances.  While both are useful risk-adjusted metrics, calling MAR Calmar is a misnomer in my opinion.

**Pull request merged**
