### PR TITLE
Update ytd and mtd calculation

### PR DESCRIPTION
**Pull request by sfjep**
**Fixed bug in YTD and MTD calculation.** 
YTD and MTD are not calculated for short return series, and are not necessarily equal to total_return. 

MTD is only assigned something other than total_return, if more than one monthly return exists - which is unnecessary. 

Same issue for YTD - but with a stricter condition of more data before it is calculated. 

MTD and YTD returns are calculated after validating that a single daily return is available. If in the same month, the dp series can be used to find MTD, else the second to last value in the mp series is used. Same method for YTD calculation.

### CODE REVIEW

**Comment by sfjep** [comment]
Does anyone see an issue with this solution? 

Just to clarify. The current approach does not allow for calculation of MTD on a portfolio started intramonth. E.g. if a portfolio started trading on 01-03-2021, no MTD return would be available today. 

Moreover, if a portfolio starts trading in 01-12-2020 and YTD is calculated on 15-01-2021, YTD will be equal to the total return as the monthly return availability conditions are breached before the correct YTD is calculated.

**Comment by timkpaine** [comment]
@sfjep is it possible to add a test/tests for this?

**Comment by sfjep** [comment]
> @sfjep is it possible to add a test/tests for this?

I added tests for the cases which I noted it currently fails. Let me know if any special cases are uncovered. 

I'm uncertain about the build errors, anything to do about it on my end?

**Comment by timkpaine** [comment]
Yes this fails lint, you can check with `make lint` and attempt to autofix with `make fix` (or use the underlying flake8 and black commands)

**Pull request merged**
